# Generated by Django 5.0 on 2024-06-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_quiz_title_question_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='quiz_title',
        ),
    ]
