# Generated by Django 5.0 on 2024-06-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_rename_quiz_question_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='assignments.quiz'),
        ),
    ]
