# Generated by Django 5.0 on 2024-08-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_quizsubmission_fail_count_quizsubmission_last_failed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedquiz',
            options={'ordering': ['completed_at']},
        ),
    ]
