# Generated by Django 5.0 on 2024-07-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_completedlesson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approval_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_eth_address',
            field=models.CharField(default='0x..', max_length=42),
        ),
    ]
