# Generated by Django 5.0 on 2024-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_approval_count_course_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_eth_address',
            field=models.CharField(default='0x..', max_length=42),
        ),
    ]
