# Generated by Django 5.0 on 2024-09-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_chapter_options'),
        ('courses', '0007_alter_chapter_options_enrollment_student_eth_address'),
    ]

    operations = [
    ]
