# Generated by Django 5.0 on 2024-09-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20240904_0340'),
        ('courses', '0008_merge_20240906_2057'),
    ]

    operations = [
    ]
